stages:
    - build
    - test

variables:
    BUILD_TYPE: Release
    GIT_SUBMODULE_STRATEGY: recursive
    EVENTS: 10

image: gitlab-registry.cern.ch/acts/machines/slc6:latest

before_script:
    # CI executor uses fail on error by default
    # setup scripts do not like that
    - set +e && source CI/setup_lcg94.sh; set -e

# check jobs
# these are technically pre-built checks and were previously in a separate
# pre-build stage. they are now part of the build stage so the user can get
# feedback from both the non-build checks and the build jobs at the same time.

format:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: none # we don't need to check core submodule
  image: gitlab-registry.cern.ch/acts/machines/check_llvm8:latest
  before_script:
    - git submodule deinit -f external/*
  script:
    - CI/check_format .
  artifacts:
    paths:
      - changed
    when: on_failure

license:
  stage: build
  image: python:alpine3.6
  variables:
    GIT_SUBMODULE_STRATEGY: none # we don't need to check core submodule
  before_script:
    - apk --no-cache add git
    - git submodule deinit -f external/*
  script:
    - CI/check_license.py .

versions:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: none # we don't need to check core submodule
  tags:
    - cvmfs
  script:
    - ./CI/show_versions.sh

# build jobs

build-minimal:
  stage: build
  tags:
    - cvmfs
  script:
    - mkdir build
    - cd build
    - cmake -GNinja -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
    - cmake --build .

build-full:
  stage: build
  tags:
    - cvmfs
  script:
    - mkdir build
    - cd build
    - cmake -GNinja -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DUSE_DD4HEP=on -DUSE_GEANT4=on -DUSE_TGEO=on -DUSE_PYTHIA8=on ..
    - cmake --build .
  artifacts:
    paths:
      - build
    expire_in: 6 hours

# test jobs

.run:
  stage: test
  tags:
    - cvmfs
  before_script:
    - set +e && source CI/setup_lcg94.sh; set -e
    - export PATH=$PWD/build/bin:$PATH

hello_world:
  extends: .run
  script:
    - ACTFWHelloWorldExample -n ${EVENTS}

generic_propagation:
  extends: .run
  script:
    - ACTFWGenericPropagationExample -n ${EVENTS}

generic_fatras_example:
  extends: .run
  script:
    - ACTFWGenericFatrasExample -n ${EVENTS}

tgeo_fatras_example:
  extends: .run
  script:
    - ACTFWTGeoFatrasExample -n ${EVENTS}

generator_particle_gun:
  extends: .run
  script:
    - ActsParticleGun -n ${EVENTS} --output-root 1 --output-csv 1

generator_pythia8:
  extends: .run
  script:
    - ActsPythia8 -n ${EVENTS} --output-root 1 --output-csv 1

generic_geometry_example:
  extends: .run
  script:
    - ACTFWGenericGeometryExample -n ${EVENTS}

dd4hep_fatras_example:
  extends: .run
  script:
    - ACTFWDD4hepFatrasExample -n ${EVENTS}

dd4hep_geometry_example:
  extends: .run
  script:
    - ACTFWDD4hepGeometryExample -n ${EVENTS}

dd4hep_propagation_example:
  extends: .run
  script:
    - ACTFWDD4hepPropagationExample -n ${EVENTS}

reproducibility_generic_propagation:
  extends: .run
  script:
    - cd scripts
    - ./testReproducibility.sh GenericPropagation ${EVENTS} propagation-steps
